### ISSUE TITLE
not an issue, just a suggestion.

### ISSUE THREAD

**Issue by mu578** [alexreinking/strsv#2]
Hello, you may try with a full vanilla C implementation: (the default layout setup compiles row-major)

https://github.com/moe123/macadam/blob/master/macadam/lapack/blas/mc_blas_trsv.h (you may extract the kernel case you are interested  in to avoid branch checking)

example: building with open-mp (you may drop open-mp if you vectorize with clang)

```
/opt/local/bin/clang-mp-9.0 -x c -std=c99  -DMC_TARGET_BUILTIN_COMPLEX=0 t.c -I/Users/M/Projects/macadam -pedantic -Wno-newline-eof /opt/local/include -L /opt/local/lib -lopenblas -Xclang -fopenmp -fopenmp-simd -DMC_TARGET_OPENMP=1 -DMC_TARGET_OPENMP_LOOP_USE_PARALLEL_FOR=1 -L /opt/local/lib/libomp -lomp
```

There are over possible hidden targets possibly calling an available ""native implementation (openblas , accelarate), however, they are not ready yet as they relays on a provided public cblas interface ... so swapping dim again... see native-gemm interface for reference. Anyhow interesting dig up. Tchuss.

**Comment by alexreinking** [comment]
I'm not sure what you're asking. Do you want me to benchmark your trsv implementation? I'm not really looking to update this repository at all, unless there's a major issue or error.

**Comment by mu578** [comment]
Ok, that's just a suggestion after all, the code is not important, however, the conclusions you drive from your study, anyways. Thank you for your time and considerations.
